import { extendZod, zUUID } from "@zodyac/zod-mongoose";
import { z } from "zod";
// Extend zod with the zId and zUUID functions (!!important)
extendZod(z); 

export const PaymentSchema = z.object({
    OderID: z.string().min(3).max(20).default("test"),
    PaymentMethod: z.string().email(),
    PaymentDateDate: z.string().email(),
    AmountPaidAmountPaid: z.string().email(),

    //default value will be generated by mongoose
    createdAt: z.date().default(new Date()), 
    updatedAt: z.date().default(new Date()),
});


// Define the schema with the ID (!!important)
export const zCustomerSchemaUdate = PaymentSchema.extend({
    _id: zUUID(), //default value will be generated by mongoose
})

export type Customer = z.infer<typeof PaymentSchema>;